# 数据集参数
dataset_conf:
  # 过滤最短的音频长度
  min_duration: 0.5
  # 最长的音频长度，大于这个长度会裁剪掉
  max_duration: 3
  # 是否裁剪静音片段
  do_vad: False
  # 音频的采样率
  sample_rate: 16000
  # 是否对音频进行音量归一化
  use_dB_normalization: True
  # 对音频进行音量归一化的音量分贝值
  target_dB: -20
  # 训练数据的数据列表路径
  train_list: 'dataset/train_list.txt'
  # 评估注册的数据列表路径
  enroll_list: 'dataset/enroll_list.txt'
  # 评估检验的数据列表路径
  trials_list: 'dataset/trials_list.txt'
  # 评估的数据要特殊处理
  eval_conf:
    # 评估的批量大小
    batch_size: 1
    # 最长的音频长度
    max_duration: 20
  # 数据加载器参数
  dataLoader:
    # 训练的批量大小
    batch_size: 16
    # 读取数据的线程数量
    num_workers: 4
  # 数据增强参数
  aug_conf:
    # 是否使用语速扰动增强，注意使用语速增强分类数量会大三倍
    speed_perturb: True
    # 是否使用音量增强
    volume_perturb: False
    # 音量增强概率
    volume_aug_prob: 0.2
    # 噪声增强的噪声文件夹
    noise_dir: 'dataset/noise'
    # 噪声增强概率
    noise_aug_prob: 0.2

# 数据预处理参数
preprocess_conf:
  # 音频预处理方法，支持：LogMelSpectrogram、MelSpectrogram、Spectrogram、MFCC、Fbank
  feature_method: 'MelSpectrogram'
  # 设置API参数，更参数查看对应API，不清楚的可以直接删除该部分，直接使用默认值
  method_args:
    sr: 16000
    n_fft: 1024
    hop_length: 320
    window: 'hann'
    win_length: 1024
    f_min: 50.0
    f_max: 14000.0
    n_mels: 64

optimizer_conf:
  # 优化方法，支持Adam、AdamW、SGD
  optimizer: 'Adam'
  weight_decay: !!float 1e-5
  # 学习率衰减函数，支持WarmupCosineSchedulerLR、CosineAnnealingLR
  scheduler: 'WarmupCosineSchedulerLR'
  # 学习率衰减函数参数
  scheduler_args:
    # 学习率的大小
    learning_rate: 0.001
    min_lr: !!float 1e-5
    warmup_epoch: 5

model_conf:
  backbone:
    # 所使用的池化层，支持ASP、SAP、TSP、TAP、TSTP
    pooling_type: 'ASP'
    embd_dim: 192
  classifier:
    # 说话人数量，即分类大小
    num_speakers: 2796
    num_blocks: 0

loss_conf:
  # 所使用的损失函数，支持AAMLoss、AMLoss、ARMLoss、CELoss
  use_loss: 'AAMLoss'
  # 损失函数参数
  args:
    margin: 0.2
    scale: 32
    easy_margin: False
  # 是否使用损失函数margin调度器
  use_margin_scheduler: True
  # margin调度器参数
  margin_scheduler_args:
    final_margin: 0.3

train_conf:
  # 训练的轮数
  max_epoch: 60
  log_interval: 100

# 所使用的模型
use_model: 'Res2Net'
